# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10qrr8LDbzQg8IyFlnorU2flofp7dgPl4
"""

def kasallik_tashxisi(belgi):
  if belgi== "Bosh og'rig'i":
    return "Bolnol iching"
  elif belgi== "Qorin og'rig'i":
    return "Esmonizan iching"
  elif belgi== "Tish og'rig'i":
    return "Qupen iching"
  else:
    return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiriting  ")
natija=kasallik_tashxisi(belgi)
print(natija)